### ISSUE TITLE
java.lang.UnsupportedOperationException: Using io.quarkus.logging.Log is only possible with Quarkus bytecode transformation; make sure the archive is indexed, for example by including a beans.xml file

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-argocd#24]
## Issue

If we execute the command `quarkus argocd application generate ` using a fresh build of the extension/plugin` we got this error
```
quarkus argocd application generate                                   
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.argocd.deployment.ArgoCDProcessor#build threw an exception: java.lang.UnsupportedOperationException: Using io.quarkus.logging.Log is only possible with Quarkus bytecode transformation; make sure the archive is indexed, for example by including a beans.xml file
        at io.quarkus.logging.Log.fail(Log.java:2927)
        at io.quarkus.logging.Log.warn(Log.java:1649)
        at io.quarkiverse.argocd.deployment.ArgoCDProcessor.build(ArgoCDProcessor.java:58)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.performCustomBuild(AugmentActionImpl.java:153)
        at io.quarkiverse.argocd.cli.application.GenerateCommand.call(GenerateCommand.java:58)
        at io.quarkiverse.argocd.cli.application.GenerateCommand.call(GenerateCommand.java:25)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.argocd.deployment.ArgoCDProcessor#build threw an exception: java.lang.UnsupportedOperationException: Using io.quarkus.logging.Log is only possible with Quarkus bytecode transformation; make sure the archive is indexed, for example by including a beans.xml file
        at io.quarkus.logging.Log.fail(Log.java:2927)
        at io.quarkus.logging.Log.warn(Log.java:1649)
        at io.quarkiverse.argocd.deployment.ArgoCDProcessor.build(ArgoCDProcessor.java:58)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
        ... 17 more
Caused by: java.lang.UnsupportedOperationException: Using io.quarkus.logging.Log is only possible with Quarkus bytecode transformation; make sure the archive is indexed, for example by including a beans.xml file
        at io.quarkus.logging.Log.fail(Log.java:2927)
        at io.quarkus.logging.Log.warn(Log.java:1649)
        at io.quarkiverse.argocd.deployment.ArgoCDProcessor.build(ArgoCDProcessor.java:58)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

**Comment by cmoulliard** [comment]
The log issue is fixed with PR #26 but we got now another error
```
/Users/cmoullia/code/ch007m/code-with-quarkus $ quarkus argocd application generate                                   
[jbang] [WARN] Detected missing or out-of-date dependencies in cache.
[jbang] Resolving dependencies...
[jbang]    io.quarkiverse.argocd:quarkus-argocd-cli:999-SNAPSHOT
[jbang] Dependencies resolved
java.lang.IllegalArgumentException: Undeclared build item class io.quarkiverse.argocd.spi.ArgoCDApplicationListBuildItem
        at io.quarkus.builder.Messages.undeclaredItem(Messages.java:13)
        at io.quarkus.builder.BuildResult.consume(BuildResult.java:50)
        at io.quarkiverse.argocd.cli.handlers.GetArgoCDApplicationHandler.accept(GetArgoCDApplicationHandler.java:14)
        at io.quarkiverse.argocd.cli.handlers.GetArgoCDApplicationHandler.accept(GetArgoCDApplicationHandler.java:10)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.performCustomBuild(AugmentActionImpl.java:160)
        at io.quarkiverse.argocd.cli.application.GenerateCommand.call(GenerateCommand.java:58)
        at io.quarkiverse.argocd.cli.application.GenerateCommand.call(GenerateCommand.java:25)
```
@iocanel
